### PR TITLE
add link to program

### PR DESCRIPTION
**Pull request by boegel**

### CODE REVIEW

**Comment by ehiggs** [comment]
:+1: only suggestion is to either remove the link for submitting talks or saying the window is closed (and also linking there).

**Comment by boegel** [comment]
done, pls check

I hope `<del>` works as I expect it to

**Comment by ehiggs** [comment]
`del` is supported everywhere but not required in the standard (it's a recommendation). So its probably OK.

**Comment by boegel** [comment]
so, let's merge and find out? :)

**Comment by ehiggs** [comment]
Please dont merge this with  stuff for '17 into '16's old page.

**Pull request closed without merging**
